kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  namespace: harvester
  name: harvester-staging-pod
  labels:
    component: harvester
    env: staging
spec:
  containers:
    - name: harvester-staging
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 20
        periodSeconds: 3
      image: docker.pkg.github.com/robin-rpr/harvester/harvester-staging:latest
      ports:
        - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: harvester-staging-deployment
  labels:
    app: harvester-staging
    env: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harvester-staging
      env: staging
  template:
    metadata:
      labels:
        app: harvester-staging
        env: staging
    spec:
      containers:
        - name: harvester-staging
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 3
          image: docker.pkg.github.com/robin-rpr/harvester/harvester-staging:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  namespace: harvester
  name: harvester-staging-node-port
spec:
  type: NodePort
  selector:
    app: harvester-staging
    env: staging
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4001
