kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  namespace: harvester
  name: harvester-local-pod
  labels:
    component: harvester
    env: local
spec:
  containers:
    - name: harvester-local
#      readinessProbe:
#        httpGet:
#          path: /
#          port: 80
#        initialDelaySeconds: 20
#        periodSeconds: 3
      image: harvester/harvester:latest
      ports:
        - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: harvester-local-deployment
  labels:
    app: harvester-local
    env: local
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harvester-local
      env: local
  template:
    metadata:
      labels:
        app: harvester-local
        env: local
    spec:
      containers:
        - name: harvester-local
          image: harvester/harvester:latest
          ports:
            - containerPort: 4000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: harvester-local-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: harvester
  labels:
      app: ingress
      env: local
spec:
  rules:
  - host: local.harvester.dev
    http:
      paths:
      - path: /.*
        backend:
          serviceName: harvester-local-node-port
          servicePort: 4000
