kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  namespace: harvester
  name: harvester-develop-pod
  labels:
    component: harvester
    env: develop
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: harvester-develop
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 20
        periodSeconds: 3
      image: registry.hub.docker.com/robinrpr/harvester/harvester-develop:latest
      ports:
        - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: harvester-develop-deployment
  labels:
    app: harvester-develop
    env: develop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harvester-develop
      env: develop
  template:
    metadata:
      labels:
        app: harvester-develop
        env: develop
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: harvester-develop
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 3
          image: registry.hub.docker.com/robinrpr/harvester/harvester-develop:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  namespace: harvester
  name: harvester-develop-node-port
spec:
  type: NodePort
  selector:
    app: harvester-develop
    env: develop
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 4001
