kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  namespace: harvester
  name: harvester-develop-pod
  labels:
    component: harvester
    env: develop
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: harvester-develop
#      readinessProbe:
#        httpGet:
#          path: /
#          port: 80
#        initialDelaySeconds: 20
#        periodSeconds: 3
      image: ghcr.io/robin-rpr/harvester-develop:latest
      ports:
        - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: harvester-develop-deployment
  labels:
    app: harvester-develop
    env: develop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: harvester-develop
      env: develop
  template:
    metadata:
      labels:
        app: harvester-develop
        env: develop
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: harvester-develop
          image: ghcr.io/robin-rpr/harvester-develop:latest
          ports:
            - containerPort: 4000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: harvester-develop-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: harvester
  labels:
      app: ingress
      env: develop
spec:
  rules:
  - host: develop.harvester.dev
    http:
      paths:
      - backend:
          serviceName: harvester-develop-node-port
          servicePort: 4000
