export enum typeEnums {
    NODE_GROUP = 'NODE_GROUP',
    MULTI_LINK = 'MULTI_LINK',
    SINGLE_LINK = 'SINGLE_LINK',
    TEXT_ELEMENT = 'TEXT_ELEMENT',
    IMAGE_ELEMENT = 'IMAGE_ELEMENT',
    HTML_ELEMENT = 'HTML_ELEMENT',
}
