version: "3.7"

networks:
  harvester-develop:

services:
  api-develop:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${DOCKER_REGISTRY_HOST}/${GITHUB_REPOSITORY}/api-develop:latest
    build:
      context: ..
      dockerfile: ./apps/api/docker/Dockerfile
      args:
        CONFIGURATION: develop
        NGINX_CONFIG: default.develop.conf
    ports:
      - "3000:3000"
    networks:
      - harvester-develop
    volumes:
      - "../:/home/node/app:ro"

  harvester-develop:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${DOCKER_REGISTRY_HOST}/${GITHUB_REPOSITORY}/harvester-develop:latest
    build:
      context: ..
      dockerfile: ./apps/harvester/docker/Dockerfile
      args:
        CONFIGURATION: develop
        NGINX_CONFIG: default.develop.conf
    ports:
      - "4000:4000"
    networks:
      - harvester-develop
    depends_on:
      - api-develop
    volumes:
      - "../:/home/node/app:ro"
