version: "3.7"

networks:
  harvester-staging:

services:
  api-staging:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${DOCKER_REGISTRY_HOST}/${GITHUB_REPOSITORY}/api-staging:latest
    build:
      context: ..
      dockerfile: ./apps/api/docker/Dockerfile
      args:
        CONFIGURATION: staging
        NGINX_CONFIG: default.staging.conf
    ports:
      - "3000:3000"
    networks:
      - harvester-staging
    volumes:
      - "../:/home/node/app:ro"

  harvester-staging:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${DOCKER_REGISTRY_HOST}/${GITHUB_REPOSITORY}/harvester-staging:latest
    build:
      context: ..
      dockerfile: ./apps/harvester/docker/Dockerfile
      args:
        CONFIGURATION: staging
        NGINX_CONFIG: default.staging.conf
    ports:
      - "4000:4000"
    networks:
      - harvester-staging
    depends_on:
      - api-staging
    volumes:
      - "../:/home/node/app:ro"

  mongodb-staging:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: mongodb
    restart: always
    ports:
      - 27017:27017
    networks:
      - harvester-staging
    environment:
      MONGO_INITDB_DATABASE: "${MONGODB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"