version: "3.7"

networks:
  harvester:

services:
  api:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: api:latest
    build:
      context: ..
      dockerfile: ./apps/api/docker/Dockerfile
      args:
        CONFIGURATION:
        NGINX_CONFIG: default.conf
    ports:
      - "3000:3000"
    networks:
      - harvester
    volumes:
      - "../:/home/node/app:ro"

  harvester:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: harvester:latest
    build:
      context: ..
      dockerfile: ./apps/harvester/docker/Dockerfile
      args:
        CONFIGURATION:
        NGINX_CONFIG: default.conf
    ports:
      - "4000:4000"
    networks:
      - harvester
    depends_on:
      - api
    volumes:
      - "../:/home/node/app:ro"
