version: "3.7"

networks:
  harvester:

services:
  api:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${DOCKER_REGISTRY_HOST}/harvester/api:latest
    build:
      context: ..
      dockerfile: ./apps/api/docker/Dockerfile
      args:
        CONFIGURATION: develop
        NGINX_CONFIG: default.develop.conf
    ports:
      - "3000:3000"
    networks:
      - harvester
    volumes:
      - "../:/home/node/app:ro"

  harvester:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${DOCKER_REGISTRY_HOST}/harvester/harvester:latest
    build:
      context: ..
      dockerfile: ./apps/harvester/docker/Dockerfile
      args:
        CONFIGURATION: develop
        NGINX_CONFIG: default.develop.conf
    ports:
      - "4000:4000"
    networks:
      - harvester
    depends_on:
      - api
    volumes:
      - "../:/home/node/app:ro"

  mongodb:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: mongodb
    restart: always
    networks:
      - harvester
    environment:
      MONGODB_DATABASE: "${MONGODB_DATABASE}"
      MONGODB_USER: "${MONGODB_USER}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"