version: "3.7"

networks:
  harvester-staging:

services:
  api-staging:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${REGISTRY_HOST}/${REGISTRY_USERNAME}/${GITHUB_REPOSITORY}/api-staging:latest
    build:
      context: ..
      dockerfile: ./apps/api/docker/Dockerfile
      args:
        CONFIGURATION: staging
        NGINX_CONFIG: default.staging.conf
    ports:
      - "3000:3000"
    networks:
      - harvester-staging
    volumes:
      - "../:/home/node/app:ro"

  harvester-staging:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${REGISTRY_HOST}/${REGISTRY_USERNAME}/${GITHUB_REPOSITORY}/harvester-staging:latest
    build:
      context: ..
      dockerfile: ./apps/harvester/docker/Dockerfile
      args:
        CONFIGURATION: staging
        NGINX_CONFIG: default.staging.conf
    ports:
      - "4000:4000"
    networks:
      - harvester-staging
    depends_on:
      - api-staging
    volumes:
      - "../:/home/node/app:ro"
