version: "3"

networks:
  harvester-prod:

services:
  api-prod:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${REGISTRY_HOST}/${REGISTRY_USERNAME}/${GITHUB_REPOSITORY}/api-prod:latest
    build:
      context: ..
      dockerfile: ./apps/api/docker/Dockerfile
      args:
        CONFIGURATION: prod
        NGINX_CONFIG: default.prod.conf
    ports:
      - "3000:3000"
    networks:
      - harvester-prod
    volumes:
      - "../:/home/node/app:ro"

  harvester-prod:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    image: ${REGISTRY_HOST}/${REGISTRY_USERNAME}/${GITHUB_REPOSITORY}/harvester-prod:latest
    build:
      context: ..
      dockerfile: ./apps/harvester/docker/Dockerfile
      args:
        CONFIGURATION: prod
        NGINX_CONFIG: default.prod.conf
    ports:
      - "4000:4000"
    networks:
      - harvester-prod
    depends_on:
      - api-prod
    volumes:
      - "../:/home/node/app:ro"

  mongodb-prod:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - harvester-prod
    environment:
      MONGO_INITDB_DATABASE: "${MONGODB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"