kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  name: api-develop-pod
  labels:
    component: api
    env: develop
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: api-develop
      image: docker.pkg.github.com/robin-rpr/harvester/api-develop:latest
      ports:
        - containerPort: 3000
    - name: mongodb-develop
      image: docker.pkg.github.com/robin-rpr/harvester/mongodb-develop:latest
      ports:
        - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-develop-deployment
  labels:
    app: api-develop
    env: develop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-develop
      env: develop
  template:
    metadata:
      labels:
        app: api-develop
        env: develop
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api-develop
          image: docker.pkg.github.com/robin-rpr/harvester/api-develop:latest
          ports:
            - containerPort: 3000
        - name: mongodb-develop
          image: docker.pkg.github.com/robin-rpr/harvester/mongodb-develop:latest
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: api-develop-node-port
spec:
  type: NodePort
  selector:
    app: api-develop
    env: develop
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-develop-deployment
  labels:
    app: api-develop
    env: prod
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb-develop
        env: develop
    spec:
      restartPolicy: Always
      containers:
        - name: mongodb-develop
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-develop-srv
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-develop
    env: develop
status:
  loadBalancer: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodata
  name: mongodata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi