kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  name: api-local-pod
  labels:
    component: api
    env: local
spec:
  containers:
    - name: api-local
      image: harvester/api:latest
      ports:
        - containerPort: 3000
    - name: mongodb-local
      image: mongo
      ports:
        - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-local-deployment
  labels:
    app: api-local
    env: local
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-local
      env: local
  template:
    metadata:
      labels:
        app: api-local
        env: local
    spec:
      restartPolicy: Always
      containers:
        - name: api-local
          image: harvester/api:latest
          ports:
            - containerPort: 3000
        - name: mongodb-local
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: api-local-node-port
spec:
  type: NodePort
  selector:
    app: api-local
    env: local
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: api-local-srv
spec:
  selector:
    app: api-local
    env: local
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017