kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  namespace: harvester
  name: api-prod-pod
  labels:
    component: api
    env: prod
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: api-prod
#      readinessProbe:
#        httpGet:
#          path: /api/status
#          port: 3000
#        initialDelaySeconds: 20
#        periodSeconds: 3
      image: ghcr.io/robin-rpr/api-prod:latest
      ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: api-prod-deployment
  labels:
    app: api-prod
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-prod
      env: prod
  template:
    metadata:
      labels:
        app: api-prod
        env: prod
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      containers:
        - name: api-prod
          image: ghcr.io/robin-rpr/api-prod:latest
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: mongodb-prod-deployment
  labels:
    app: api-prod
    env: prod
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb-prod
      env: prod
  template:
    metadata:
      labels:
        app: mongodb-prod
        env: prod
    spec:
      restartPolicy: Always
      containers:
        - name: mongodb-prod
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: harvester
  name: mongodb-prod-srv
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-prod
    env: prod
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodata
  labels:
      app: mongodata
      env: prod
spec:
  capacity:
    storage: 15Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: mongodata
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: harvester
  creationTimestamp: null
  labels:
    app: mongodata-claim
    env: prod
  name: mongodata-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      app: mongodata
      env: prod
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-prod-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  namespace: harvester
  labels:
      app: ingress
      env: prod
spec:
  rules:
  - host: api.harvester.dev
    http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: api-prod-node-port
          servicePort: 3000
  - host: "*.proxy.harvester.dev"
    http:
      paths:
      - path: /?(.*)
        backend:
          serviceName: api-prod-node-port
          servicePort: 3000
