kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  namespace: harvester
  name: api-develop-pod
  labels:
    component: api
    env: develop
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: api-develop
#      readinessProbe:
#        httpGet:
#          path: /api/status
#          port: 3000
#        initialDelaySeconds: 20
#        periodSeconds: 3
      image: ghcr.io/robin-rpr/api-develop:latest
      ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: api-develop-deployment
  labels:
    app: api-develop
    env: develop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-develop
      env: develop
  template:
    metadata:
      labels:
        app: api-develop
        env: develop
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      containers:
        - name: api-develop
          image: ghcr.io/robin-rpr/api-develop:latest
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: mongodb-develop-deployment
  labels:
    app: api-develop
    env: develop
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb-develop
      env: develop
  template:
    metadata:
      labels:
        app: mongodb-develop
        env: develop
    spec:
      restartPolicy: Always
      containers:
        - name: mongodb-develop
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: harvester
  name: mongodb-develop-srv
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-develop
    env: develop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: harvester
  creationTimestamp: null
  labels:
    app: mongodata
    env: develop
  name: mongodata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-develop-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: harvester
  labels:
      app: ingress
      env: develop
spec:
  rules:
  - host: develop.api.harvester.dev
    http:
      paths:
      - backend:
          serviceName: api-develop-node-port
          servicePort: 3000
  - host: "*.proxy.harvester.dev"
    http:
      paths:
      - backend:
          serviceName: api-prod-node-port
          servicePort: 3000
