kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  name: api-develop-pod
  labels:
    component: api
    env: develop
spec:
  containers:
    - name: api-develop
      image: docker.pkg.github.com/robin-rpr/harvester/api-develop:latest
      ports:
        - containerPort: 3000
    - name: mongodb-develop
      image: docker.pkg.github.com/robin-rpr/harvester/mongodb-develop:latest
      ports:
        - containerPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-develop-deployment
  labels:
    app: api-develop
    env: develop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-develop
      env: develop
  template:
    metadata:
      labels:
        app: api-develop
        env: develop
    spec:
      containers:
        - name: api-develop
          image: docker.pkg.github.com/robin-rpr/harvester/api-develop:latest
          ports:
            - containerPort: 3000
        - name: mongodb-develop
          image: docker.pkg.github.com/robin-rpr/harvester/mongodb-develop:latest
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: api-develop-node-port
spec:
  type: NodePort
  selector:
    app: api-develop
    env: develop
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: api-develop-srv
spec:
  selector:
    app: api-develop
    env: develop
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017