kind: Namespace
apiVersion: v1
metadata:
  name: harvester
  labels:
    name: harvester
---
apiVersion: v1
kind: Pod
metadata:
  namespace: harvester
  name: api-staging-pod
  labels:
    component: api
    env: staging
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: api-staging
#      readinessProbe:
#        httpGet:
#          path: /api/status
#          port: 3000
#        initialDelaySeconds: 20
#        periodSeconds: 3
      image: ghcr.io/robin-rpr/api-staging:latest
      ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: api-staging-deployment
  labels:
    app: api-staging
    env: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-staging
      env: staging
  template:
    metadata:
      labels:
        app: api-staging
        env: staging
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      containers:
        - name: api-staging
          image: ghcr.io/robin-rpr/api-staging:latest
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: harvester
  name: mongodb-staging-deployment
  labels:
    app: api-staging
    env: staging
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb-staging
      env: staging
  template:
    metadata:
      labels:
        app: mongodb-staging
        env: staging
    spec:
      restartPolicy: Always
      containers:
        - name: mongodb-staging
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodata
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: mongodata-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: harvester
  name: mongodb-staging-srv
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb-staging
    env: staging
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: harvester
  creationTimestamp: null
  labels:
    app: mongodata
    env: staging
  name: mongodata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-staging-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: harvester
  labels:
      app: ingress
      env: staging
spec:
  rules:
  - host: staging.api.harvester.dev
    http:
      paths:
      - backend:
          serviceName: api-staging-node-port
          servicePort: 3000
  - host: "*.proxy.harvester.dev"
    http:
      paths:
      - backend:
          serviceName: api-prod-node-port
          servicePort: 3000
